# Generated by Django 4.2.9 on 2024-06-28 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0002_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="WatchedMovie",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("adult", models.BooleanField(default=False)),
                ("backdrop_path", models.CharField(blank=True, max_length=255)),
                ("genre_ids", models.JSONField()),
                ("original_language", models.CharField(max_length=10)),
                ("original_title", models.CharField(max_length=510)),
                ("overview", models.TextField()),
                ("popularity", models.DecimalField(decimal_places=3, max_digits=10)),
                ("poster_path", models.CharField(blank=True, max_length=255)),
                ("release_date", models.DateField()),
                ("title", models.CharField(max_length=510)),
                ("video", models.BooleanField(default=False)),
                ("vote_average", models.DecimalField(decimal_places=3, max_digits=5)),
                ("vote_count", models.PositiveIntegerField()),
                ("watched_at", models.DateTimeField(auto_now_add=True)),
                ("times_watched", models.PositiveIntegerField(default=1)),
                ("profile", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="users.profile")),
            ],
            options={
                "verbose_name": "Movie",
                "verbose_name_plural": "Movies",
                "ordering": ["id"],
            },
        ),
        migrations.AddConstraint(
            model_name="watchedmovie",
            constraint=models.UniqueConstraint(
                fields=("original_title", "release_date"),
                name="unique_original_title_release_date",
                violation_error_message="This movie has already been watched.",
            ),
        ),
    ]
