# Generated by Django 4.2.9 on 2024-08-13 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0003_user_email_verified"),
    ]

    operations = [
        migrations.CreateModel(
            name="ViewDetails",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("watched_at", models.DateTimeField(auto_now_add=True)),
                ("rating", models.PositiveIntegerField(blank=True, null=True)),
                ("comment", models.TextField(blank=True)),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("es", "Spanish"),
                            ("fr", "French"),
                            ("de", "German"),
                            ("it", "Italian"),
                            ("pt", "Portuguese"),
                            ("ru", "Russian"),
                            ("ja", "Japanese"),
                            ("zh", "Chinese"),
                            ("ko", "Korean"),
                            ("ar", "Arabic"),
                            ("hi", "Hindi"),
                            ("other", "Other"),
                        ],
                        default="en",
                        max_length=10,
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        choices=[
                            ("cinema", "Movie Theater"),
                            ("home", "Home"),
                            ("friend", "Friend's House"),
                            ("other", "Other"),
                        ],
                        default="home",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "verbose_name": "View Details",
                "verbose_name_plural": "View Details",
                "ordering": ["-watched_at"],
            },
        ),
        migrations.CreateModel(
            name="WatchedMovie",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("adult", models.BooleanField(default=False)),
                ("backdrop_path", models.CharField(blank=True, max_length=255)),
                ("genre_ids", models.JSONField()),
                ("original_language", models.CharField(max_length=10)),
                ("original_title", models.CharField(max_length=510)),
                ("overview", models.TextField()),
                ("popularity", models.DecimalField(decimal_places=3, max_digits=10)),
                ("poster_path", models.CharField(blank=True, max_length=255)),
                ("release_date", models.DateField()),
                ("title", models.CharField(max_length=510)),
                ("video", models.BooleanField(default=False)),
                ("vote_average", models.DecimalField(decimal_places=3, max_digits=5)),
                ("vote_count", models.PositiveIntegerField()),
            ],
            options={
                "verbose_name": "Movie",
                "verbose_name_plural": "Movies",
                "ordering": ["id"],
            },
        ),
        migrations.AddConstraint(
            model_name="watchedmovie",
            constraint=models.UniqueConstraint(
                fields=("original_title", "release_date"),
                name="unique_original_title_release_date",
                violation_error_message="This movie has already been watched.",
            ),
        ),
        migrations.AddField(
            model_name="viewdetails",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="view_details", to="users.profile"
            ),
        ),
        migrations.AddField(
            model_name="viewdetails",
            name="watched_movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="view_details", to="movies.watchedmovie"
            ),
        ),
    ]
