# Generated by Django 4.2.9 on 2024-08-27 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="watchedmovie",
            name="unique_original_title_release_date",
        ),
    ]
