# Generated by Django 5.1 on 2024-09-05 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0003_rename_title_watchedmovie_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="watchedmovie",
            old_name="release_date",
            new_name="first_air_date",
        ),
    ]
