# Generated by Django 5.1 on 2024-09-05 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0005_rename_original_name_watchedmovie_original_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watchedmovie",
            name="overview",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="watchedmovie",
            name="release_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
