# Generated by Django 5.1 on 2025-02-28 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0010_alter_viewdetails_language_alter_viewdetails_place"),
        ("users", "0003_user_email_verified"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="viewdetails",
            options={
                "ordering": ["watched_date"],
                "verbose_name": "View Details",
                "verbose_name_plural": "View Details",
            },
        ),
        migrations.CreateModel(
            name="PlanToWatch",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_to_watch",
                        to="movies.watchedmovie",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="plan_to_watch", to="users.profile"
                    ),
                ),
            ],
            options={
                "verbose_name": "Plan to Watch",
                "verbose_name_plural": "Plans to Watch",
                "ordering": ["-added_at"],
                "unique_together": {("movie", "profile")},
            },
        ),
    ]
