# Generated by Django 5.1 on 2025-03-26 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0011_alter_viewdetails_options_plantowatch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watchedmovie",
            name="popularity",
            field=models.DecimalField(decimal_places=14, max_digits=20),
        ),
    ]
