# Generated by Django 5.1 on 2025-03-26 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0012_alter_watchedmovie_popularity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watchedmovie",
            name="popularity",
            field=models.DecimalField(decimal_places=20, max_digits=40),
        ),
    ]
