#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python manage.py migrate
python /app/manage.py collectstatic --noinput

echo "Ejecuta gunicorn"
gunicorn --forwarded-allow-ips="*" --pythonpath ./config watchedmovies.wsgi:application --workers=1 --bind ["0.0.0.0"]
