#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python manage.py migrate
python /app/manage.py collectstatic --noinput

echo "Ejecuta gunicorn"
exec /usr/local/bin/gunicorn config.wsgi --forwarded-allow-ips="*" --workers=1 --bind ["0.0.0.0"]
